config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "top" => "homes#top", as: "top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"

    resources :games, only: [:show, :create]
    resources :reviews do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get  "/users/information" => "users#show"
    get  "/users/information/edit" => "users#edit"
    patch "/users/information" => "users#update"
    get "/users/unsubscribe" => "users#unsubscribe"
    patch "/users/withdraw" => "users#withdraw"

    get "search" => "searches#search"
    get "games_search" => "games#search"
    patch "/reviews/:id/edit" => "reviews#update"
    get "search_tag" => "reviews#search_tag"
    
    get "favorite_rank" => "ranks#favorite_rank"
    get "comment_rank" => "ranks#comment_rank"
    get "game_rank" => "ranks#game_rank"
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
    
  validates :comment, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :user_id
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  self.primary_key = "jan"
  has_many :reviews, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :comment,presence:true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :comment, presence: true
end

app/models/rank.rb
class Rank < ApplicationRecord
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game, primary_key: "jan"
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :review_and_tags, dependent: :destroy
  has_many :review_tags, through: :review_and_tags

  validates :comment, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :rate_count, -> { order(rate: :desc) }

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @review = Review.where("comment LIKE?", "#{word}")
    elsif search == "forward_match"
      @review = Review.where("comment LIKE?", "#{word}%")
    elsif search == "backward_match"
      @review = Review.where("comment LIKE?", "%#{word}")
    elsif search == "partial_match"
      @review = Review.where("comment LIKE?", "%#{word}%")
    else
      @review = Review.all
    end
  end

  def review_status
    if is_deleted == true
      "削除"
    else
      "有効"
    end
  end

  def save_review_tags(tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.review_tags.pluck(:name) unless self.review_tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.review_tags.delete ReviewTag.find_by(name: old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      review_tag = ReviewTag.find_or_create_by(name: new_name)
      self.review_tags << review_tag
    end
  end
end

app/models/review_and_tag.rb
# frozen_string_literal: true

class ReviewAndTag < ApplicationRecord
  belongs_to :review
  belongs_to :review_tag
end

app/models/review_tag.rb
# frozen_string_literal: true

class ReviewTag < ApplicationRecord
  has_many :review_and_tags, dependent: :destroy
  has_many :reviews, through: :review_and_tags

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_one_attached :profile_image

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :rate_count, -> { order(rate: :desc) }

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/admin/reviews_controller.rb
# frozen_string_literal: true

class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_review, only: [:show, :edit, :update]

  def index
    @reviews = Review.page(params[:page])
  end

  def show
    @review = Review.find(params[:id])
    @tag_list = @review.review_tags.pluck(:name).join(",")
    @review_tags = @review.review_tags
  end

  def edit
    @review = Review.find(params[:id])
    @tag_list = @review.review_tags.pluck(:name).join(",")
  end

  def update
    @review = Review.find(params[:id])
    tag_list = params[:review][:name].split(",")
    if @review.update(review_params)
      @review.save_review_tags(tag_list)
      redirect_to admin_review_path(@review)
      flash[:notice] = "レビューの編集に成功しました。"
    else
      flash.now[:alart_flash] = "レビューの編集に失敗しました。"
      render "edit"
    end
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path
  end

  private
    def review_params
      params.require(:review).permit(:user_id, :game_id, :rate, :comment, :is_deleted)
    end

    def ensure_review
      @review = Review.find(params[:id])
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/comments_helper.rb
# frozen_string_literal: true

module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
# frozen_string_literal: true

module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/tagsearches_helper.rb
# frozen_string_literal: true

module TagsearchesHelper
end

app/views/admin/reviews/edit.html.erb
<%= render"layouts/error_messages", model: @review %>
<div class="container mt-4">
  <div class="row justify-content-center mb-3">
    <div class="col-md-8">
    
      <div class="justify-content-center mb-3">
        <div class="col-md-12">
          <h4><strong><%= @review.game.title%></strong>のレビュー編集</h4>
        </div>
      </div>

        <%= form_with model: @review, url:admin_review_path, method: :patch do |f| %>
          <div class="mt-3">
            <%= f.label :レビュー,class:"form-label" %>
          </div>
          <div>
            <%= f.text_area :comment, autocomplete: "comment",class:"form-control", size: "20x10" %>
          </div>
          <div class="mt-3">
            <label>タグ(,で区切ると複数タグ登録できます)</label>
            <%= f.text_field :name,value: @tag_list, class: 'form-control' %>
          </div>
          <div class="mt-3">
            <%= f.label :評価,class:"form-label" %>
            <%= f.hidden_field :rate, autocomplete: "rate",class:"form-control" %>
              <div id="post_raty"></div>
              <script>
                  let elem = document.querySelector('#post_raty');
            
                  let opt = {  
                    starOn: "<%= asset_path('star-on.png') %>",
                    starOff: "<%= asset_path('star-off.png') %>",
                    starHalf: "<%= asset_path('star-half.png') %>",
                    scoreName: 'review[rate]',
                  };
                  raty(elem, opt);
              </script>
          </div>
          <div class="row mt-3">
            <div class="col-md-4">
              <%= f.label :is_deleted,"ステータス" %>
            </div>
            <div class="col-md-2">
              <%= f.radio_button :is_deleted, :false,class:"form-check-input" %>
              <%= f.label :is_deleted, "有効",class:"form-check-label" %>
            </div>
            <div class="col-md-4">
              <%= f.radio_button :is_deleted, :true,class:"form-check-input" %>
              <%= f.label :is_deleted, "削除",class:"form-check-label" %>
            </div>
          </div>
  
          <div class=" mt-3 text-center">
            <%= f.submit "変更を保存", class: "btn btn-success"%>
          </div>
  
        <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "戻る", :back, class: "btn btn-md btn-secondary mt-3" %>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div class= 'container mt-4'>
  <div class="col-md-10 mx-auto">
    <div class="row justify-content-center mb-3">
      <div class="col-md-12">
        <h4>投稿一覧</h4>
      </div>
    </div>

    <table class ="table table-bordered border-dark table-hover align-middle">
      <thead class="bg-secondary">
        <tr align="center">
          <th scope="col" style="width: 10%">ID</th>
          <th scope="col" style="width: 40%">タイトル</th>
          <th scope="col" style="width: 50%">レビュー</th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review|%>
        <tr align="center">
        <td><%= review.id %></td>
        <td>
          <%= link_to admin_review_path(review.id), class:"text-dark border-bottom" do  %>
          <%= review.game.title %>
          <% end %>
        </td>
        <td><%= review.comment %></td>
        <% end %>
      </tbody>
    </table>
    <div class="row justify-content-center">
      <%= paginate @reviews %>
    </div>
    
  </div>
</div>

app/views/admin/reviews/show.html.erb
<div class="container mt-4">
  <div class="col-md-12 mx-auto">

    <div class="row justify-content-center mb-3">
      <div class="col-md-8 headline">
        <h4><strong><%= @review.game.title%></strong>のレビュー詳細</h4>
      </div>
    </div>

    <div class="col-md-6 text-center mx-auto">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th scope="col" style="width: 30%"></th>
            <th scope="col" style="width: 70%"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>ID</td>
            <td><%= @review.id %></td>
          </tr>
          <tr>
            <td>タイトル</td>
            <td><%= @review.game.title %></td>
          </tr>
          <tr>
            <td>レビュー</td>
            <td><%= @review.comment %></td>
          </tr>
          <tr>
            <td>タグ</td>
            <td>
              <% @review_tags.each do |tag| %>
              <i class="fas fa-tag"></i>
                <%= tag.name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>評価</td>
            <td id="rate_<%= @review.id %>"></td>
            <script>
              let elem = document.querySelector('#rate_<%= @review.id %>');
  
              let opt = {  
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                score: "<%= @review.rate %>",
                readOnly: true,
              };
              raty(elem, opt);
            </script>
          </tr>
          <tr>
            <td>ステータス</td>
            <td>
              <% if @review.is_deleted == true %>
              <strong style="color:darkgray;"><%= "削除" %></strong>
              <% else %>
              <strong style="color:green;"><%= "有効" %></strong>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="d-flex justify-content-center">
    <td><%= link_to "編集する", edit_admin_review_path(@review.id), class: "btn btn-success change_button mt-3"%></td>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "戻る", admin_reviews_path, class: "btn btn-md btn-secondary mt-5" %>
  </div>
  
</div>