config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "top" => "homes#top", as: "top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"

    resources :games, only: [:show, :create]
    resources :reviews do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get  "/users/information" => "users#show"
    get  "/users/information/edit" => "users#edit"
    patch "/users/information" => "users#update"
    get "/users/unsubscribe" => "users#unsubscribe"
    patch "/users/withdraw" => "users#withdraw"

    get "search" => "searches#search"
    get "games_search" => "games#search"
    patch "/reviews/:id/edit" => "reviews#update"
    get "search_tag" => "reviews#search_tag"
    
    get "favorite_rank" => "ranks#favorite_rank"
    get "comment_rank" => "ranks#comment_rank"
    get "game_rank" => "ranks#game_rank"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_one_attached :profile_image

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :rate_count, -> { order(rate: :desc) }

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_user, only: [:show, :edit, :update]

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user.update(user_params) ? (redirect_to admin_user_path(@user)) : (render :edit)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :is_deleted)
    end

    def ensure_user
      @user = User.find(params[:id])
    end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<%= render"layouts/error_messages", model: @user %>
<div class="container mt-4">
  <div class="row justify-content-center mb-3">
    <div class="col-md-8">
    
      <div class="justify-content-center mb-3">
        <div class="col-md-10">
          <h4><strong><%= @user.name%></strong>さんの会員情報編集</h4>
        </div>
      </div>

        <%= form_with model: @user, url:admin_user_path, method: :patch do |f| %>
          <table class="table table-borderless">
            <thead>
              <tr>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.label :ニックネーム,class:"col-form-label" %></td>
                <td><%= f.text_field :name, autofocus: true, autocomplete: "name",class:"form-control" %></td>
              </tr>
              <tr>
                 <td><%= f.label :メールアドレス,class:"col-form-label mt-3" %></td>
                 <td><%= f.email_field :email, autocomplete: "email",class:"form-control mt-3" %></td>
              </tr>
              <tr>
                <td>
                  <%= f.label :is_deleted,"ステータス",class:"form-label mt-3" %>
                </td>
                <td>
                  <%= f.radio_button :is_deleted, :false,class:"col-form-check-input mt-3" %>
                  <%= f.label :is_deleted, "有効",class:"form-check-label mt-3" %>
                </td>
                <td>
                  <%= f.radio_button :is_deleted, :true,class:"col-form-check-input mt-3" %>
                  <%= f.label :is_deleted, "退会",class:"form-check-label mt-3" %>
                </td>
              </tr>
            </tbody>
          </table>
  
          <div class="mt-3 text-center">
            <%= f.submit "変更を保存", class: "btn btn-success"%>
          </div>
  
        <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "戻る", :back, class: "btn btn-md btn-secondary mt-3" %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class= 'container mt-4'>
  <div class="col-md-10 mx-auto">
    <div class="row justify-content-center mb-3">
      <div class="col-md-12">
        <h4>ユーザ一覧</h4>
      </div>
    </div>

    <table class ="table table-bordered border-dark table-hover align-middle">
      <thead class="bg-secondary">
        <tr align="center">
          <th scope="col" style="width: 10%">ID</th>
          <th scope="col" style="width: 30%">ニックネーム</th>
          <th scope="col" style="width: 40%">メールアドレス</th>
          <th scope="col" style="width: 20%">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user|%>
        <tr align="center">
        <td><%= user.id %></td>
        <td>
          <%= link_to admin_user_path(user.id), class:"text-dark border-bottom" do  %>
          <%= user.name %>
          <% end %>
        </td>
        <td><%= user.email %></td>
        <td>
          <% if user.is_deleted == true %>
          <strong style="color:darkgray;"><%= "退会" %></strong>
          <% else %>
          <strong style="color:green;"><%= "有効" %></strong>
          <% end %>
        </td>
        <% end %>
      </tbody>
    </table>
    <div class="row justify-content-center">
      <%= paginate @users %>
    </div>
    
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container mt-4">
  <div class="col-md-12 mx-auto">

    <div class="row justify-content-center mb-3">
      <div class="col-md-8 headline">
        <h4><strong><%= @user.name%></strong>さんのユーザ詳細</h4>
      </div>
    </div>
    
    <div class="col-md-6 text-center mx-auto">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th scope="col" style="width: 30%"></th>
            <th scope="col" style="width: 70%"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>ID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>
            <td>ニックネーム</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td>ステータス</td>
            <td>
              <% if @user.is_deleted == true %>
              <strong style="color:darkgray;"><%= "退会" %></strong>
              <% else %>
              <strong style="color:green;"><%= "有効" %></strong>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="d-flex justify-content-center">
    <td><%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-success change_button mt-3"%></td>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "戻る", admin_users_path, class: "btn btn-md btn-secondary mt-5" %>
  </div>
  
</div>