config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "top" => "homes#top", as: "top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  # ユーザー用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"

    resources :games, only: [:show, :create]
    resources :reviews do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    # users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get  "/users/information" => "users#show"
    get  "/users/information/edit" => "users#edit"
    patch "/users/information" => "users#update"
    get "/users/unsubscribe" => "users#unsubscribe"
    patch "/users/withdraw" => "users#withdraw"

    get "search" => "searches#search"
    get "games_search" => "games#search"
    patch "/reviews/:id/edit" => "reviews#update"
    get "search_tag" => "reviews#search_tag"
    
    get "favorite_rank" => "ranks#favorite_rank"
    get "comment_rank" => "ranks#comment_rank"
    get "game_rank" => "ranks#game_rank"
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
    
  validates :comment, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :user_id
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  self.primary_key = "jan"
  has_many :reviews, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :comment,presence:true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :comment, presence: true
end

app/models/rank.rb
class Rank < ApplicationRecord
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game, primary_key: "jan"
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :review_and_tags, dependent: :destroy
  has_many :review_tags, through: :review_and_tags

  validates :comment, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :rate_count, -> { order(rate: :desc) }

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @review = Review.where("comment LIKE?", "#{word}")
    elsif search == "forward_match"
      @review = Review.where("comment LIKE?", "#{word}%")
    elsif search == "backward_match"
      @review = Review.where("comment LIKE?", "%#{word}")
    elsif search == "partial_match"
      @review = Review.where("comment LIKE?", "%#{word}%")
    else
      @review = Review.all
    end
  end

  def review_status
    if is_deleted == true
      "削除"
    else
      "有効"
    end
  end

  def save_review_tags(tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.review_tags.pluck(:name) unless self.review_tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old_name|
      self.review_tags.delete ReviewTag.find_by(name: old_name)
    end

    # 新しいタグを保存
    new_tags.each do |new_name|
      review_tag = ReviewTag.find_or_create_by(name: new_name)
      self.review_tags << review_tag
    end
  end
end

app/models/review_and_tag.rb
# frozen_string_literal: true

class ReviewAndTag < ApplicationRecord
  belongs_to :review
  belongs_to :review_tag
end

app/models/review_tag.rb
# frozen_string_literal: true

class ReviewTag < ApplicationRecord
  has_many :review_and_tags, dependent: :destroy
  has_many :reviews, through: :review_and_tags

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_one_attached :profile_image

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "ゲストユーザー"
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :rate_count, -> { order(rate: :desc) }

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

app/helpers/admin/comments_helper.rb
# frozen_string_literal: true

module Admin::CommentsHelper
end

app/helpers/admin/posts_helper.rb
# frozen_string_literal: true

module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/tagsearches_helper.rb
# frozen_string_literal: true

module TagsearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="p-3">
  <div class="text-center mt-3">
    <div class="row">
      <div class="col-md-4 offset-md-4">© All Rights Reserved by Game Memory</div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg text-center navbar-dark bg-info">
  <div class="navbar-collapse">
    <% if user_signed_in? %>
    <div class="row d-flex justify-content-around align-items-center col-md-6 ms-5">
      <div class="navbar navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size: '70x70' %>
        <% end %>
      </div>
    </div>
    <h5 style="color: white;">ようこそ、<%= current_user.name %>さん</h5>
    <% elsif admin_signed_in? %>
    <div class="row d-flex justify-content-around align-items-center col-md-6 ms-5">
      <div class="navbar navbar-brand">
        <%= link_to admin_top_path do %>
          <%= image_tag 'logo.jpg', size: '70x70' %>
        <% end %>
      </div>
    </div>
    <% else %>
    <div class="row d-flex justify-content-around align-items-center col-md-6 ms-5">
      <div class="navbar navbar-brand">
        <%= link_to root_path do %>
          <%= image_tag 'logo.jpg', size: '70x70' %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mx-auto justify-content-around">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to users_information_path , class: "nav-link text-light" do %>
          <i class="fas fa-user-alt fa-lg" style="color: #ffffff;"></i>マイページ
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to games_search_path , class: "nav-link text-light" do %>
          <i class="fas fa-search fa-lg" style="color: #ffffff;"></i>ゲームを探す
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to reviews_path , class: "nav-link text-light" do %>
          <i class="fas fa-gamepad fa-lg" style="color: #ffffff;"></i>投稿一覧
          <% end %>
        </li>
        <li class="nav-item">
          <div class="dropdown nav-link">
            <a href="#" class="dropdown-toggle text-light" data-toggle="dropdown">
              <i class="fas fa-trophy fa-lg" style="color: #ffffff"></i>ランキング
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "いいね",favorite_rank_path , class: "dropdown-item" %></li>
              <li><%= link_to "コメント",comment_rank_path , class: "dropdown-item" %></li>
              <li><%= link_to "ゲーム",game_rank_path , class: "dropdown-item" %></li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
          <i class="fas fa-sign-out-alt fa-lg" style="color: #ffffff;"></i>ログアウト
          <% end %>
        </li>
      <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to admin_reviews_path , class: "nav-link text-light" do %>
          <i class="fas fa-gamepad fa-lg" style="color: #ffffff;"></i>投稿一覧
          <% end %>
        <li class="nav-item">
          <%= link_to admin_users_path , class: "nav-link text-light" do %>
          <i class="fas fa-users fa-lg" style="color: #ffffff;"></i>ユーザ一覧
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light" do %>
          <i class="fas fa-sign-out-alt fa-lg" style="color: #ffffff;"></i>ログアウト
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to reviews_path, class: "nav-link text-light" do %>
          <i class="fas fa-gamepad fa-lg" style="color: #ffffff;"></i>投稿一覧
          <% end %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
          <i class="fas fa-user-plus fa-lg" style="color: #ffffff;"></i>新規登録
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link text-light" do %>
          <i class="fas fa-sign-in-alt fa-lg" style="color: #ffffff;"></i>ログイン
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_guest_sign_in_path, class: "nav-link text-light", method: :post do %>
          <i class="fas fa-user-tie fa-lg" style="color: #ffffff;"></i>ゲストログイン
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_search.html.erb
<div class="serch_form" >
  <table align="center">
    <tr>
      <td>
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word %>
          <%= f.select :range, options_for_select([['Review'], ['User']]) %>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
          <%= f.submit "検索", class: "btn btn-sm btn-secondary" %>
        <% end %>
      </td>
    </tr> 
  </table>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameMemory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/475dfdea42.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>

  </head>

  <body data-turbolinks="false">
    
    <header>
    <%= render 'layouts/header' %>
    </header>
    
    <main>
      <div class="text-white bg-secondary mt-3 text-center">
        <h5><%= flash[:notice] %></h5>
      </div>
      <%= yield %>
    </main>
    
    <footer>
    <%= render 'layouts/footer' %>
    </footer>
    
  </body>
</html>